//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegendaryUmbrella.LockFile.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LegendaryUmbrella.LockFile.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens a handle to a file and waits for the user to exit.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The r, w, and d flags may be combined, although there must be no spaces. When combining multiple flags, extra dashes are not required..
        /// </summary>
        internal static string HelpNotes {
            get {
                return ResourceManager.GetString("HelpNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opened handle to file. Press CTRL+C to exit....
        /// </summary>
        internal static string OpenSuccess {
            get {
                return ResourceManager.GetString("OpenSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows other processes to delete the file.
        /// </summary>
        internal static string ParamAllowDelete {
            get {
                return ResourceManager.GetString("ParamAllowDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows other processes to read the file (default).
        /// </summary>
        internal static string ParamAllowRead {
            get {
                return ResourceManager.GetString("ParamAllowRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows other processes to write to the file.
        /// </summary>
        internal static string ParamAllowWrite {
            get {
                return ResourceManager.GetString("ParamAllowWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the file to open. The user account must have read permissions for the file specified.
        /// </summary>
        internal static string ParamFile {
            get {
                return ResourceManager.GetString("ParamFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denies all access to a file.
        /// </summary>
        internal static string ParamNoAccess {
            get {
                return ResourceManager.GetString("ParamNoAccess", resourceCulture);
            }
        }
    }
}
